// Vragen voor de Puzzel ronde
// Vier kernantwoorden horen bij één verband
const puzzelQuestions = [
  { link: "Plaag", answers: ["Onheil", "Muizen", "Straf van God", "Stoot"], remarks: "Dit verband draait om het woord 'plaag'. Vraag kandidaten of zij de 10 plagen van Egypte kennen." },
  { link: "Lof", answers: ["Der zotheid", "Bladgewas", "Brussels", "Slagen met"] },
  { link: "Pruimen", answers: ["Jam", "Tabak kauwen", "Gedroogde", "Dat is niet te"] },
  { link: "Koers", answers: ["Vast", "Prijs van een aandeel", "Route", "Wielrenwedstrijd"] },
  { link: "Boksen", answers: ["Met je vuisten vechten", "Iets voor elkaar", "Kick", "Tegen iets op"] },
  { link: "Letter", answers: ["Druk", "Greep", "Geschreven taalteken", "Banket"] },
  { link: "Rol", answers: ["Mops", "In de hoofd", "WC", "Persoon in een film"] },
  { link: "Borg", answers: ["Pen", "Staan voor iemand", "Björn", "Garantie in geldvorm"] },
  { link: "Zalm", answers: ["Gerookte", "Trekvis", "Het neusje van de", "Kleur"] },
  { link: "Stuk", answers: ["Munt", "Niet heel", "Toneel", "Portie"] },
  { link: "Band", answers: ["Vriendschap", "Autowiel", "Muziekgroep", "Video"] },
  { link: "Kop", answers: ["Kranten", "Hoofd", "Of munt", "Drinkbeker"] },
  { link: "Diskjockey", answers: ["DJ in het lang", "Kiest platen", "Letterlijk 'schijvenruiter'", "Radio"] },
  { link: "Ice", answers: ["Age", "Cold as", "Engels bevroren water", "In Case of Emergency"]},
  { link: "DIY", answers: ["Doe het zelf", "Afkorting", "In het Engels", "Voor handige Harry's"]},
  { link: "Klavertje 4", answers: ["Brengt geluk", "Heeft drie blaadjes", "Zoeken in de tuin", "Komt niet veel voor"]  },
  { link: "Kangoeroe", answers: ["Heeft een buidel", "Kan hoog springen", "Leeft in Australië", "Walibi is er een"]  },
  { link: "Duitse kranten", answers: ["Bild", "Die Welt", "Der Tagesspiegel", "Berliner Zeitung"]  },
  { link: "Bedriegen", answers: ["Liegen en", "Ontrouw zijn", "Schijn doet het", "Vreemdgaan"]  },
  { link: "Breaking Bad", answers: ["Gus Fring", "Jesse Pinkman", "Saul Goodman", "Walter White"]  },
  { link: "Zappen", answers: ["Ander programma opzetten", "Switchen", "Tussen TV-zenders", "Met de afstandsbediening"]  },
  { link: "Lawine", answers: ["Héél veel sneeuw", "Rennen!", "Gevaarlijk voor skiërs", "Die van de berg glijdt"]  },
  { link: "Toren", answers: ["Eiffel", "Van Pisa", "Vuur", "Klok"]  },
  { link: "Popcorn", answers: ["In de bioscoop", "Maïs", "Snack", "Zoet of zout"]  },
  { link: "Kerk", answers: ["Biechtstoel", "Altaar", "Sacristie", "De kogel is door de"]  },
  { link: "Augurk", answers: ["Familie van de komkommer", "Pickle", "Vaak op een burger", "Kesbeke"] },
  { link: "Complot", answers: ["Theorie", "Samenzwering", "De maanlanding is nep!", "Klinkt als appelmoes"]  },
  { link: "Er was eens..", answers: ["Zo beginnen sprookjes", "Once upon a time", "En ze leefden nog lang en gelukkig", "Il était une fois"] },
  { link: "Ex", answers: ["On the beach", "Odus", "Je voormalige partner", "Lat"]},
  { link: "22", answers: ["Catch-..", "11 + 11", "Taylor Swift voelt zich zo", "Twee Voetbalteams"]},
  { link: "Handige Harry", answers: ["Voor een doe-het-zelfer", "Niet 'Klunzige Klaas", "Allitererende uitdrukking", "Of 'Lompe Louis'"]},
  { link: "Boten", answers: ["Catamaran", "Fregat", "Kano", "Tanker"] },
  { link: "Fair Play", answers: ["Niet 'Injust Stop'", "Sporten volgens de regels", "En de juiste normen", "Engelse term"] },
  { link: "Raven", answers: ["..sburger", "Feesten", "Niet 'eksters'", "Niet 'kraaien'"] },
  { link: "Vechtsporten", answers: ["MMA", "Aikido", "Capoeira", "Krav Maga"] },
  { link: "Jantje", answers: ["... Smit", "Vaak het onderwerp van moppen", "Niet 'Pietje'", "Zag eens pruimen hangen"] },
  { link: "Rijn", answers: ["Manda...", "Europese rivier", "Stroomt door Duitsland", "Keulen ligt eraan"]},
  { link: "Lil", answers: ["Wayne", "Nas X", "Uzi Vert", "Klein"] },
  { link: "Hostel", answers: ["Synoniem voor jeugdherberg", "Met z'n allen in de slaapzaal", "Goedkoper dan een hotel", "Overnachten"] },
  { link: "Pop", answers: ["...art", "...corn", "Iggy ...", "Soort speelgoed"] },
  { link: "Tosti", answers: ["Ham en kaas", "Uit het ijzer", "Broodklapper", "Warme hap"] },
  { link: "Groningen", answers: ["Ommelanden", "Martinitoren", "Provincie", "Stad"] },
  { link: "TVTAS", answers: ["Texel", "Vlieland", "Terschelling", "Ameland en Schiermonnikoog"] },
  { link: "Willem", answers: ["Van Oranje", "Alexander", "De W van ...", "Ome ..."] },
  { link: "Thee", answers: ["Chai", "Darjeeling", "Oolong", "Soms met bubbles"] },
  { link: "Pensioen", answers: ["Je moet niet meer werken", "AOW", "In Nederland op je 67e", "En je krijgt toch geld!"] },
  { link: "Tiger", answers: ["... Woods", "Flying ...", "... King", "Eye of the ..."] },
  { link: "Bumperkleven", answers: ["Agressief rijgedrag", "In het verkeer", "Kort op voorganger rijden", "Oorzaak van ongevallen"] },
  { link: "112", answers: ["7 * 16", "1456 : 13", "Noodnummer", "Bel een ambulance!" ]},
  { link: "Chill", answers: ["Rustig!", "Winston Chur...", "Jongerentaal", "Koud"] },
  { link: "Seizoen", answers: ["Het weer verandert", "Jaargetijde", "Er zijn er vier", "21 december start het volgende"] },
  { link: "Ochtend", answers: ["...humeur", "...spits", "...stond", "Je ontbijt erin"] },
  { link: "Pinkpop", answers: ["Niet 'Purplerock'", "Veel artiesten", "Landgraaf", "Sinds 1970"] },
  { link: "Sushi", answers: ["Rijst", "Vis", "Japans gerecht", "Wasabi"]  },
  { link: "Zomer", answers: ["Lange schoolvakantie", "...hit", "Zon, zee en strand", "Warme dagen"] },
  { link: "Emoticon", answers: ["Smileys", "In berichten", "NotLikeThis", "PogChamp"]  },
  { link: "Twitch", answers: ["Livestreams", "Gaming", "Justin.tv", "Platform"]  },
  { link: "Wie is de Mol?", answers: ["Televisieprogramma", "Eén saboteur", "Negen kandidaten", "Vlaams format"]  },
  { link: "Bellen", answers: ["Mij niet ...", "Oor...", "Snotte...", "Zeep..."]},
  { link: "Zes", answers: ["666:111", "Aantal poten van een insect", "Zijden van een dobbelsteen", "Het ...de zintuig"]  },
  { link: "Bluetooth", answers: ["Blauwe tand", "Draadloos", "Verbinding", "Harald"]},
  { link: "Bullshit", answers: ["Stierenkak ...", "Onzin", "Kletskoek", "... in het Engels"]},
  { link: "Hell", answers: ["Highway to ...", "...s Angels", "Onderwereld", "What the ..."]},
  { link: "Broadway", answers: ["'Brede Weg'", "Cats", "New York", "Phantom of the Opera"]},
  { link: "Comic Sans", answers: ["Lettertype", "Ziet er kinderachtig uit", "Wordt vaak gehaat", "Ziet er zo uit"]},
  { link: "Rock & Roll", answers: ["Elvis Presley", "'Steen en rollen'", "Muziekgenre", "Elektrische gitaar"]},
  { link: "Drugs", answers: ["Coke, speed, hasj, LSD, ...", "XTC, Crack, GHB, ...", "Hard of soft", "...hond"]},
  { link: "Meter", answers: ["100 cm", "Baro...", "Kilo...", "Thermo..."]},
  { link: "Hotels", answers: ["Van der Valk", "Ibis", "Hilton", "Fletcher"]},
];
